services:
  client:
    container_name: lotrcli-container
    build: ./Frontend
    ports:
      - "5173:5173"
    networks:
      - lotr-net
    environment:
      - VITE_API_URL=http://server:3000/api/v1
    depends_on:
      - server

  server:
    container_name: lotrsrv-container
    build: ./Backend
    ports:
      - "3000:3000"
    networks:
      - lotr-net

networks:
  lotr-net:
    driver: bridge