services:
  client:
    container_name: "lotrcli-container"
    ports:
      - "5173:5173"
    networks:
      - "lotr-net"
    build: "./Frontend"

  server:
    container_name: "lotrsrv-container"
    ports:
      - "3000:3000"
    networks: 
      - "lotr-net"
    build: "./Backend"

networks:
  lotr-net:
    driver: bridge
